services:
  server-container:
    build:
      context: ./Server
      dockerfile: Dockerfile
    image: server-container:latest
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080.
    environment:
      - ASPNETCORE_URLS=http://+:8080  # Ensure app listens on 8080.
    networks:
      server-network:
        aliases:
          - server-container.local

  prometheus-container:
    image: prom/prometheus:latest
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Custom Prometheus config.
    ports:
      - "9090:9090"  # Default Prometheus UI port.
    networks:
      server-network:
        aliases:
          - prometheus-container.local
    depends_on:
      - server-container

  grafana-container:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  # Default Grafana UI port.
    volumes:
      - ./Grafana/server_dashboard.json:/etc/grafana/provisioning/dashboards/server_dashboard.json
      - ./Grafana/grafana-dashboard-provisioning.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./Grafana/grafana-datasource-provisioning.yml:/etc/grafana/provisioning/datasources/datasource.yml  # Ensure this line is present
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default admin password.
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      server-network:
        aliases:
          - grafana-container.local
    depends_on:
      - prometheus-container

networks:
  server-network:
    driver: bridge
