{
 "title": "Server Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "System Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "Up/Down"
    },
    {
     "expr": "100 * sum(rate(process_cpu_seconds_total{job=\"$job\"}[5m])) by (instance)\n\n\n",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * process_working_set_bytes{job=\"$job\"} / system_memory_total_bytes{job=\"$job\"}",
     "legendFormat": "Memory Usage (%)"
    }
   ]
  },
  {
   "title": ".NET Stats",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"$job\"}/(1024 * 1024)",
     "legendFormat": ".NET Memory (MB)"
    },
    {
     "expr": "sum(changes(system_runtime_dotnet_gc_collections{job=\"$job\"}[5m]))",
     "legendFormat": "GC Events (5 min)"
    }
   ]
  },
  {
   "title": "User Stats",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "successful_user_adds{job=\"$job\"}",
     "legendFormat": "Successful Adds"
    },
    {
     "expr": "failed_user_adds{job=\"$job\"}",
     "legendFormat": "Failed Adds"
    },
    {
     "expr": "successful_user_deletes{job=\"$job\"}",
     "legendFormat": "Successful Deletes"
    },
    {
     "expr": "failed_user_deletes{job=\"$job\"}",
     "legendFormat": "Failed Deletes"
    },
    {
     "expr": "successful_user_clears{job=\"$job\"}",
     "legendFormat": "Successful Clears"
    },
    {
     "expr": "failed_user_clears{job=\"$job\"}",
     "legendFormat": "Failed Clears"
    },
    {
     "expr": "num_active_users{job=\"$job\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "HTTP Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{method=\"POST\", job=\"$job\"}[5m])) or vector(0)",
     "legendFormat": "POST (5 min)"
    },
    {
     "expr": "sum(increase(http_requests_received_total{method=\"GET\", job=\"$job\"}[5m])) or vector(0)",
     "legendFormat": "GET (5 min)"
    }
   ]
  }
 ]
}