name: Deploy to ECS

on:
  push:
    branches:
      - main  # Trigger on push to main branch.
  workflow_dispatch:  # Manual trigger for troubleshooting.


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code.
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for building the image.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Amazon ECR.
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Build and push Docker image to ECR.
      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: server  # ECR repo name.
          IMAGE_TAG: ${{ github.sha }}  # Unique tag based on commit SHA.
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Set up Terraform.
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0  # Adjust to your version.

      # Initialize Terraform.
      - name: Terraform Init
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      # Apply Terraform changes.
      - name: Terraform Apply
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform apply -auto-approve -var "docker_image=${{ steps.login-ecr.outputs.registry }}/server:${{ github.sha }}"
